---
    version: '3.5'
  
    services:
      picsgalore:
        container_name: python_picsgalore
        image: "picsgalore:dev"
        build:
          context: .
        volumes:
          - .:/usr/src/app
        logging:
          driver: json-file
          options:
            max-size: 10m
            max-file: "2"
        ports:
          - "5000:5000"
        expose:
          - 5000
        env_file:
          - ./api_keys.env
        restart: always
        depends_on:
          - redis
      redis:
        image: redis:alpine